# Generated by Django 5.1.6 on 2025-02-09 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='mane',
            new_name='name',
        ),
    ]
