# Generated by Django 5.2.2 on 2025-06-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="last_name",
            field=models.CharField(max_length=251),
        ),
    ]
