# Generated by Django 5.2.5 on 2025-08-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='not defined', max_length=6),
        ),
    ]
