# Generated by Django 5.2.6 on 2025-09-17 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gender',
            new_name='Genre',
        ),
    ]
