# Generated by Django 4.0.2 on 2024-06-14 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='firsts_name',
            new_name='first_name',
        ),
    ]
