# Generated by Django 4.0.2 on 2023-09-09 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Genre',
        ),
    ]
