# Generated by Django 4.0.2 on 2024-02-09 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='first_name',
            new_name='name',
        ),
    ]
