# Generated by Django 4.0.2 on 2022-10-19 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='firts_name',
            new_name='first_name',
        ),
    ]
