# Generated by Django 4.0.2 on 2023-09-03 12:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Actor",
        ),
        migrations.DeleteModel(
            name="Genre",
        ),
    ]
