# Generated by Django 4.0.2 on 2024-01-06 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gener',
            new_name='Genre',
        ),
    ]
