# Generated by Django 4.0.2 on 2023-02-14 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Table',
            new_name='Actor',
        ),
    ]
