# Generated by Django 4.0.2 on 2022-06-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
