# Generated by Django 5.2.2 on 2025-06-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_alter_actor_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="last_name",
            field=models.CharField(max_length=255),
        ),
    ]
