# Generated by Django 4.0.2 on 2024-12-19 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_rename_name_genre_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre',
            new_name='name',
        ),
    ]
