# Generated by Django 4.0.2 on 2023-02-28 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_actorformat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActorFormat',
            new_name='Actor',
        ),
        migrations.RenameModel(
            old_name='GenreFormat',
            new_name='Genre',
        ),
    ]
