# Generated by Django 4.0.2 on 2024-05-22 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_genpythonre_delete_genre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genpythonre',
            new_name='Genre',
        ),
    ]
