# Generated by Django 5.2.8 on 2026-01-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_genre_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='actor',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_actor_full_name'),
        ),
    ]
