# Generated by Django 4.0.2 on 2022-08-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_rename_actor_actors_rename_genre_genres'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actors',
            new_name='Actor',
        ),
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
    ]
