# Generated by Django 4.0.2 on 2023-03-08 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_rename_first_name_actor_first_nam_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='first_nam',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='actor',
            old_name='last_nam',
            new_name='last_name',
        ),
    ]
