# Generated by Django 4.0.2 on 2025-03-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_actor_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
