# Generated by Django 4.0.2 on 2024-09-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_actor_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
